# Generated by Django 5.0.1 on 2024-08-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_authentication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authentication',
            old_name='username',
            new_name='email',
        ),
    ]
