# Generated by Django 5.0.1 on 2024-08-27 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_delete_authentication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
