# Generated by Django 5.0.1 on 2024-09-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auditoriuminfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MVHallInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('facilities', models.TextField()),
            ],
        ),
    ]
