# Generated by Django 5.0.1 on 2024-10-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_uploadfileform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFileForm',
            new_name='UploadFile',
        ),
    ]
