# Generated by Django 5.1 on 2024-10-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_mvhalluploadfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MVHallUploadFile',
            new_name='MVHallFiles',
        ),
    ]
