# Generated by Django 5.1 on 2024-10-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_mvhalluploadfile_mvhallfiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFile',
            new_name='AuditoriumFiles',
        ),
    ]
